POST http://localhost:5500/api/item
Content-Type: application/json

{
    "item": "This is the test todo item"
}

###

GET http://localhost:5500/api/items
Content-Type: application/json


###

PUT http://localhost:5500/api/item/624b03a4b9294ba722f5af25
Content-Type: application/json

{
    "item": "This is the second todo item updated !!" 
}

###

DELETE http://localhost:5500/api/item/624b03a4b9294ba722f5af25
Content-Type: application/json


###

POST http://localhost:5500/users
Content-Type: application/json

{
    "email": "romain.matheos.31@gmail.com",
    "password" : "motdepasse",
    "firstname" : "Romain",
    "lastname" : "Matheos",
    "creatAt" : "19/11/1998"
}

### 

GET http://localhost:5500/users
Content-Type: application/json

###

POST http://localhost:5500/habit
Content-Type: application/json

{
    "habit": "Reveil 6h",
    "condition" : "No snooze",
    "user_email": "romain.matheos.31@gmail.com"
}

###

GET http://localhost:5500/habit
Content-Type: application/json

###

PUT http://localhost:5500/habit/625496569d8cfd3d9ab6c234
Content-Type: application/json

{
    "className" : ["box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green", "box-green"]
}

### 
POST http://localhost:5500/planning
Content-Type: application/json

{
    "day": "LUNDI",
    "user_email": "romain.matheos.31@gmail.com",
    "content": []
}


###


PUT http://localhost:5500/planning/6256e71f6e8ab9c90015ab5d
Content-Type: application/json

{
    "content" : [{
        "start": 1,
        "end": 3,
        "text": "jour"
    }]
}

###

GET http://localhost:5500/planning
Content-Type: application/json
###

POST http://localhost:5500/color
Content-Type: application/json

{
    "user_email": "jean@jean.com",
    "self": "rgb(0, 139, 2) none repeat scroll 0% 0%",
    "work": "rgb(184, 0, 0) none repeat scroll 0% 0%",
    "obligate": "rgb(219, 62, 0) none repeat scroll 0% 0%",
    "relax": "rgb(252, 203, 0) none repeat scroll 0% 0%"
}

### 

PUT http://localhost:5500/color/62592855ae13c66eb4db8c8d
Content-Type: application/json

{
    "self": "rgb(0, 139, 2)",
    "work": "rgb(184, 0, 0)",
    "obligate": "rgb(219, 62, 0)",
    "relax": "rgb(252, 203, 0)"
}

###

GET http://localhost:5500/color
Content-Type: application/json

###

POST http://localhost:5500/login
Content-Type: application/json

{
    "email": "romain.matheos.31@gmail.com",
    "password" : "Motdepasse"
}
